import type { Semester, Subject, TypeMeta } from "./types";
import { makeSubjectSlug } from "./slug";

type RawSubject = Omit<Subject, "slug">;
type RawSemester = Omit<Semester, "subjects"> & { subjects: RawSubject[] };

/**
 * Raw semester data — single source of truth for the entire site.
 * Source: PCI B.Pharm NEP 2020 syllabus (implementation 2026–27 onwards).
 */
const RAW_SEMESTERS: RawSemester[] = [
    {
        num: 1,
        credits: 21,
        color: "#4C6EF5",
        bg: "#EEF2FF",
        badge: "#C7D2FE",
        label: "Python + Core Sciences",
        subjects: [
            {
                code: "BP101T",
                name: "Basics of Python Programming for Pharmaceutical Sciences",
                credits: 2,
                type: "T",
                highlight: true,
                units: [
                    "Unit I: Intro to Python — variables, data types, control flow, loops",
                    "Unit II: Functions, modules, NumPy, Pandas for pharmacy data",
                    "Unit III: File handling, data visualization with Matplotlib",
                    "Unit IV: Python in drug data analysis & pharmaceutical calculations",
                    "Unit V: Automation scripts for pharmacy workflows",
                ],
            },
            {
                code: "BP102T",
                name: "General Pharmacy",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: History & scope of pharmacy in India; pharmacy profession",
                    "Unit II: Pharmaceutical dosage forms — classification & overview",
                    "Unit III: Routes of drug administration and drug delivery concepts",
                    "Unit IV: Drugs & Cosmetics Act overview; pharmacy legislation",
                    "Unit V: Pharmacy practice, patient counseling basics",
                ],
            },
            {
                code: "BP103T",
                name: "Healthcare Psychology and Communication Skills",
                credits: 1,
                type: "T",
                units: [
                    "Unit I: Fundamentals of healthcare psychology",
                    "Unit II: Patient behavior, motivation, medication adherence",
                    "Unit III: Verbal and non-verbal communication skills",
                    "Unit IV: Counseling skills for pharmacists",
                    "Unit V: Interprofessional communication in healthcare settings",
                ],
            },
            {
                code: "BP104T",
                name: "Human Anatomy, Physiology and Pathophysiology I",
                credits: 4,
                type: "T",
                units: [
                    "Unit I: Cell biology — structure, organelles, cell cycle",
                    "Unit II: Cardiovascular system — heart anatomy, cardiac cycle, BP regulation",
                    "Unit III: Respiratory system — lungs, breathing mechanics, gas exchange",
                    "Unit IV: Blood — composition, haematopoiesis, blood groups",
                    "Unit V: Pathophysiology of hypertension, cardiac failure, asthma",
                ],
            },
            {
                code: "BP105T",
                name: "Introduction to Pharmacognosy",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: History, scope and development of pharmacognosy",
                    "Unit II: Classification of crude drugs (morphological, chemical, etc.)",
                    "Unit III: Plant morphology and anatomy relevant to drug identification",
                    "Unit IV: Primary and secondary metabolites — types and significance",
                    "Unit V: Quality control and adulteration of crude drugs",
                ],
            },
            {
                code: "BP106T",
                name: "Pharmaceutical Inorganic and Analytical Chemistry",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Impurities in pharmaceuticals; limits tests (Arsenic, Lead, Iron)",
                    "Unit II: Major inorganic pharmaceutical compounds — acids, bases, salts",
                    "Unit III: Volumetric analysis — acid-base, redox, complexometric titrations",
                    "Unit IV: Gravimetric analysis — principles and pharmaceutical applications",
                    "Unit V: Pharmaceutical water — types, purification, quality specifications",
                ],
            },
            {
                code: "BP107P-BP111P",
                name: "Practicals — General Pharmacy, HPCS, Anatomy, Pharmacognosy, Inorganic Chemistry",
                credits: 5,
                type: "P",
                units: [
                    "General Pharmacy Lab — dispensing, calculations, dosage form prep",
                    "Healthcare Psychology — role plays, communication exercises",
                    "Anatomy & Physiology — microscopy, models, physiology experiments",
                    "Pharmacognosy — identification of crude drugs, organoleptic tests",
                    "Inorganic Chemistry — limit tests, titrations, gravimetric experiments",
                ],
            },
        ],
    },
    {
        num: 2,
        credits: 26,
        color: "#10B981",
        bg: "#ECFDF5",
        badge: "#A7F3D0",
        label: "Organic Chemistry + Biostatistics",
        subjects: [
            {
                code: "BP201T",
                name: "Applied Biostatistics and Data Analytics for Pharmaceutical Sciences",
                credits: 2,
                type: "T",
                highlight: true,
                units: [
                    "Unit I: Intro to biostatistics; types of data; scales of measurement",
                    "Unit II: Measures of central tendency and dispersion; frequency distribution",
                    "Unit III: Probability distributions — Normal, Binomial, Poisson",
                    "Unit IV: Hypothesis testing — t-test, ANOVA, Chi-square test",
                    "Unit V: Regression, correlation; pharmaceutical data analytics using Python/Excel",
                ],
            },
            {
                code: "BP202T",
                name: "Biochemistry",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Carbohydrates — structure, glycolysis, TCA cycle, gluconeogenesis",
                    "Unit II: Lipids — fatty acids, beta-oxidation, lipoproteins, cholesterol",
                    "Unit III: Proteins — amino acids, peptide bonds, enzyme kinetics (Michaelis-Menten)",
                    "Unit IV: Nucleic acids — DNA replication, transcription, translation, gene expression",
                    "Unit V: Vitamins, coenzymes and their pharmaceutical relevance; clinical biochemistry",
                ],
            },
            {
                code: "BP203T",
                name: "Human Anatomy, Physiology and Pathophysiology II",
                credits: 4,
                type: "T",
                units: [
                    "Unit I: Digestive system — GI tract anatomy, digestion, absorption mechanisms",
                    "Unit II: Endocrine system — hormones, feedback regulation, diabetes pathophysiology",
                    "Unit III: Nervous system — neuron structure, CNS/PNS, neurotransmitters, synapse",
                    "Unit IV: Renal system — nephron structure, urine formation, renal regulation of BP",
                    "Unit V: Reproductive system; pathophysiology of GI disorders, renal failure",
                ],
            },
            {
                code: "BP204T",
                name: "Pharmaceutical Organic Chemistry",
                credits: 4,
                type: "T",
                units: [
                    "Unit I: Bonding, hybridization, electronic effects (inductive, mesomeric)",
                    "Unit II: Aliphatic hydrocarbons — alkanes, alkenes, alkynes; reactions",
                    "Unit III: Aromatic compounds — benzene, aromaticity, electrophilic aromatic substitution",
                    "Unit IV: Functional groups — alcohols, aldehydes, ketones, carboxylic acids",
                    "Unit V: Amines, amides, stereoisomerism — enantiomers, diastereomers, R/S naming",
                ],
            },
            {
                code: "BP205T",
                name: "Pharmacognosy and Phytochemistry",
                credits: 4,
                type: "T",
                units: [
                    "Unit I: Alkaloids — classification, general extraction, examples (morphine, quinine)",
                    "Unit II: Glycosides — types (cardiac, anthraquinone, saponin), medicinally important ones",
                    "Unit III: Volatile oils — composition, properties, pharmaceutical uses",
                    "Unit IV: Tannins, flavonoids, terpenoids — chemistry and applications",
                    "Unit V: Phytochemical screening, plant drug standardization techniques",
                ],
            },
            {
                code: "BP206T",
                name: "Physical Pharmaceutics",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: States of matter; thermodynamics; intermolecular forces in pharma",
                    "Unit II: Solutions — solubility theories, dissolution kinetics, diffusion",
                    "Unit III: Surface and interfacial phenomena — surface tension, surfactants, HLB",
                    "Unit IV: Colloidal dispersions; emulsions, suspensions — stability and formulation",
                    "Unit V: Rheology — viscosity, flow properties of pharmaceutical systems",
                ],
            },
            {
                code: "BP207P-BP212P-SEC",
                name: "Practicals + SEC Elective",
                credits: 7,
                type: "P",
                units: [
                    "Biochemistry Lab — enzyme assays, protein estimation, metabolite tests",
                    "Anatomy Physiology II Lab — experiments on digestive, renal, nerve physiology",
                    "Organic Chemistry Lab — synthesis, melting point, TLC, functional group tests",
                    "Pharmacognosy Lab — phytochemical tests, alkaloid & glycoside identification",
                    "Physical Pharmaceutics Lab — viscosity, solubility, surface tension measurements",
                    "SEC Elective (choose 1): Communication Skills | Mental Well-Being & Stress Mgmt | Fundamentals of Computer Operations",
                ],
            },
        ],
    },
    {
        num: 3,
        credits: 25,
        color: "#F59E0B",
        bg: "#FFFBEB",
        badge: "#FDE68A",
        label: "Machine Learning + Pharmacology",
        subjects: [
            {
                code: "BP301T",
                name: "Introduction to Machine Learning in Pharmaceutical Sciences",
                credits: 2,
                type: "T",
                highlight: true,
                units: [
                    "Unit I: ML fundamentals — supervised, unsupervised, reinforcement learning overview",
                    "Unit II: Data preprocessing, feature engineering for pharmaceutical datasets",
                    "Unit III: Regression and classification algorithms — Linear Regression, Decision Tree, kNN",
                    "Unit IV: Clustering — k-means, hierarchical; dimensionality reduction (PCA)",
                    "Unit V: ML applications in QSAR, virtual screening, pharmacokinetics prediction",
                ],
            },
            {
                code: "BP302T",
                name: "Environmental Sciences",
                credits: 1,
                type: "T",
                units: [
                    "Unit I: Ecosystems, biodiversity, environmental pollution types and effects",
                    "Unit II: Pharmaceutical waste management; green pharmacy principles",
                    "Unit III: SDGs in healthcare; environmental regulations for pharma industry",
                ],
            },
            {
                code: "BP303T",
                name: "Ethics and Universal Human Values",
                credits: 1,
                type: "T",
                units: [
                    "Unit I: Ethics fundamentals; professional ethics in pharmacy practice",
                    "Unit II: Universal human values — respect, empathy, honesty in patient care",
                    "Unit III: Research ethics — informed consent, plagiarism, authorship",
                ],
            },
            {
                code: "BP304T",
                name: "General Pharmacology",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Routes of drug administration; pharmacokinetics — ADME in detail",
                    "Unit II: Pharmacodynamics — receptor theories, dose-response relationships",
                    "Unit III: Drug metabolism — Phase I/II reactions, CYP enzymes, first-pass effect",
                    "Unit IV: Adverse drug reactions — classification, mechanisms, pharmacogenomics",
                    "Unit V: Drug interactions — pharmacokinetic & pharmacodynamic; clinical significance",
                ],
            },
            {
                code: "BP305T",
                name: "Heterocyclic Compounds and Stereochemistry",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Stereochemistry — chirality, optical activity, enantiomers, R/S configuration",
                    "Unit II: 5-membered heterocycles — furan, thiophene, pyrrole, imidazole, pyrazole",
                    "Unit III: 6-membered heterocycles — pyridine, pyrimidine, pyrazine, piperazine",
                    "Unit IV: Fused ring systems — quinoline, isoquinoline, indole, benzimidazole",
                    "Unit V: Pharmaceutical significance of heterocyclic drugs — NSAIDs, antibiotics, antivirals",
                ],
            },
            {
                code: "BP306T",
                name: "Pharmaceutical Dosage Forms I",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Tablets — formulation, manufacture (direct compression, wet granulation), QC",
                    "Unit II: Capsules — hard and soft gelatin capsules; formulation and evaluation",
                    "Unit III: Liquid dosage forms — solutions, syrups, elixirs, suspensions, emulsions",
                    "Unit IV: Powders and granules — preparation, characterization, packaging",
                    "Unit V: Topical preparations — ointments, creams, gels, pastes; formulation & evaluation",
                ],
            },
            {
                code: "BP307T",
                name: "Pharmaceutical Engineering",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Size reduction — laws, types of mills; size separation — sieves, classifiers",
                    "Unit II: Mixing — principles, types of mixers; fluid flow in pharmaceutical systems",
                    "Unit III: Heat transfer — conduction, convection; evaporation; distillation types",
                    "Unit IV: Drying — theory, psychrometry; types of dryers (tray, spray, freeze)",
                    "Unit V: Filtration and centrifugation; crystallization; GMP in engineering operations",
                ],
            },
            {
                code: "BP308T",
                name: "Pharmaceutical Microbiology",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Microbiology fundamentals — classification, growth, culture methods",
                    "Unit II: Sterilization methods — thermal, filtration, radiation, gaseous",
                    "Unit III: Sterility testing; microbial limit tests (MLT); pyrogen testing",
                    "Unit IV: Antibiotics — mechanism of action, resistance mechanisms, classification",
                    "Unit V: Vaccines and immunology basics; microbiological quality control in industry",
                ],
            },
            {
                code: "BP309P-AEC",
                name: "Practicals + AEC Elective",
                credits: 6,
                type: "P",
                units: [
                    "General Pharmacology Lab — in vitro and in vivo experiments, animal ethics",
                    "Heterocyclic Chemistry Lab — synthesis, characterization, melting point",
                    "Dosage Forms Lab — tablet compression, capsule filling, liquid preparation",
                    "AEC Option 1: Nutraceuticals and Functional Foods",
                    "AEC Option 2: Food Analysis",
                    "AEC Option 3: Yoga and Life Sciences",
                ],
            },
        ],
    },
    {
        num: 4,
        credits: 23,
        color: "#EC4899",
        bg: "#FDF2F8",
        badge: "#FBCFE8",
        label: "Medicinal Chemistry + 1st Internship",
        subjects: [
            {
                code: "BP401T",
                name: "Herbal Drug Technology",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: WHO guidelines for herbal medicines; global regulatory overview",
                    "Unit II: GAP — cultivation, harvesting, collection of medicinal plants",
                    "Unit III: Extraction methods — maceration, percolation, Soxhlet, supercritical CO2",
                    "Unit IV: Herbal formulations — types, manufacture, packaging",
                    "Unit V: Quality control, standardization, pharmacopoeial standards for herbal drugs",
                ],
            },
            {
                code: "BP402T",
                name: "Medicinal Chemistry",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Drug-receptor interactions; SAR principles; bioisosterism",
                    "Unit II: Analgesics and NSAIDs — opioids, aspirin, paracetamol SAR",
                    "Unit III: Cardiovascular drugs — antihypertensives, antiarrhythmics, antithrombotics",
                    "Unit IV: Antibacterial agents — sulfonamides, fluoroquinolones, beta-lactams SAR",
                    "Unit V: CNS drugs — sedatives, hypnotics, antipsychotics, antidepressants SAR",
                ],
            },
            {
                code: "BP403T",
                name: "Pharmaceutical Biotechnology",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Recombinant DNA technology — restriction enzymes, vectors, gene cloning",
                    "Unit II: Fermentation technology — types of fermenters, scale-up, downstream processing",
                    "Unit III: Monoclonal antibodies — hybridoma technology, therapeutic applications",
                    "Unit IV: Vaccines — production, adjuvants, live, killed, subunit vaccines",
                    "Unit V: Biosimilars, genomics, proteomics, pharmacogenomics in drug development",
                ],
            },
            {
                code: "BP404T",
                name: "Social Pharmacy and Public Health",
                credits: 2,
                type: "T",
                units: [
                    "Unit I: Social determinants of health; epidemiology basics; disease burden in India",
                    "Unit II: National health programs — NHM, immunization schedule, TB, HIV, malaria",
                    "Unit III: Essential medicines concept; Janaushadhi scheme; generic prescribing",
                    "Unit IV: Pharmacoeconomics — cost-benefit, cost-effectiveness analysis; QALY",
                    "Unit V: Pharmacist in community health; rational drug use; polypharmacy issues",
                ],
            },
            {
                code: "BP405T",
                name: "Systemic Pharmacology I",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: ANS pharmacology — cholinergic agonists/antagonists, adrenergic drugs",
                    "Unit II: CNS pharmacology — sedatives, anxiolytics, antiepileptics, anti-Parkinson",
                    "Unit III: Cardiovascular pharmacology — antihypertensives, diuretics, cardiac glycosides",
                    "Unit IV: GI pharmacology — antacids, H2 blockers, PPIs, laxatives, antiemetics",
                    "Unit V: Respiratory pharmacology — bronchodilators, corticosteroids, antitussives",
                ],
            },
            {
                code: "BP411I",
                name: "Internship I (Mandatory)",
                credits: 4,
                type: "I",
                units: [
                    "Mandatory industrial / hospital / community pharmacy internship",
                    "Minimum 120 hours of experiential learning",
                    "Structured diary, activities log and internship report",
                    "Oral viva examination for credit award",
                    "Placements: manufacturing plants, hospital pharmacy, community stores, regulatory firms",
                ],
            },
        ],
    },
    {
        num: 5,
        credits: 22,
        color: "#8B5CF6",
        bg: "#F5F3FF",
        badge: "#DDD6FE",
        label: "QA + Innovation + Drug Delivery",
        subjects: [
            {
                code: "BP501T",
                name: "Biomedicinal Chemistry",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Drug design — rational, combinatorial and fragment-based approaches",
                    "Unit II: QSAR — Hansch analysis, Free-Wilson method, CoMFA",
                    "Unit III: Antiviral and anticancer agents — mechanisms and SAR",
                    "Unit IV: Antidiabetic (biguanides, TZDs, DPP-4 inhibitors) and antilipidemic drugs",
                    "Unit V: Prodrug concept, soft drugs, bioisosterism in drug design examples",
                ],
            },
            {
                code: "BP502T",
                name: "Industrial Pharmacognosy",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Commercial production of important plant drugs (opium, belladonna, digitalis)",
                    "Unit II: Phytopharmaceuticals in global markets — trends and trade",
                    "Unit III: Industrial extraction, isolation and purification techniques at large scale",
                    "Unit IV: Standardization and validation of herbal products for market",
                    "Unit V: Regulatory requirements — WHO, EMA, AYUSH, FSSAI for herbal products",
                ],
            },
            {
                code: "BP503T",
                name: "Innovation and Startup Ecosystem",
                credits: 2,
                type: "T",
                highlight: true,
                units: [
                    "Unit I: Innovation models — design thinking, lean startup methodology in pharma",
                    "Unit II: Startup ecosystem — incubators, accelerators, government schemes (Startup India)",
                    "Unit III: IPR basics for pharmaceutical innovations; patent search strategies",
                    "Unit IV: Business model canvas; MVP development; market sizing for pharma products",
                    "Unit V: Case studies — pharma startups, AI-based health-tech companies in India",
                ],
            },
            {
                code: "BP504T",
                name: "Pharmaceutical Dosage Form II",
                credits: 2,
                type: "T",
                units: [
                    "Unit I: Controlled release drug delivery — matrix, reservoir, osmotic systems",
                    "Unit II: Transdermal drug delivery — patches, enhancers, in vitro permeation",
                    "Unit III: Ocular and nasal drug delivery systems",
                    "Unit IV: Targeted drug delivery — nanoparticles, liposomes, solid lipid nanoparticles",
                    "Unit V: BCS classification; in vitro-in vivo correlations (IVIVC)",
                ],
            },
            {
                code: "BP505T",
                name: "Pharmaceutical Quality Assurance",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Quality concepts — TQM, quality circles, quality by design (QbD)",
                    "Unit II: GMP — Schedule M (India), WHO GMP, ICH Q7 for API manufacture",
                    "Unit III: Validation — process, analytical method, cleaning, equipment validation",
                    "Unit IV: Audits — internal, vendor; documentation: SOPs, BMR, BPR",
                    "Unit V: ICH guidelines overview; accelerated and long-term stability studies",
                ],
            },
            {
                code: "BP506T",
                name: "Systemic Pharmacology II",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Endocrine pharmacology — insulin types, oral hypoglycemics, thyroid drugs",
                    "Unit II: Chemotherapy — antibiotics, antifungals, antivirals, antiprotozoals",
                    "Unit III: Immunopharmacology — immunosuppressants, immunostimulants, biologics",
                    "Unit IV: Dermatological and ophthalmological pharmacology",
                    "Unit V: Reproductive pharmacology — contraceptives, fertility drugs, oxytocics",
                ],
            },
        ],
    },
    {
        num: 6,
        credits: 26,
        color: "#06B6D4",
        bg: "#ECFEFF",
        badge: "#A5F3FC",
        label: "AI in Pharma + Analysis + Internship II",
        subjects: [
            {
                code: "BP604T",
                name: "AI Applications in Pharmaceutical Sciences",
                credits: 2,
                type: "T",
                highlight: true,
                units: [
                    "Unit I: Overview of AI/ML pipeline in drug discovery (target ID to lead optimization)",
                    "Unit II: Deep learning for molecular property prediction — GNN, transformer models",
                    "Unit III: NLP in pharmacovigilance — literature mining, adverse event extraction",
                    "Unit IV: AI in clinical trials — patient stratification, adaptive trial design",
                    "Unit V: CADD tools — AutoDock, Schrödinger; AI-integrated docking workflows",
                ],
            },
            {
                code: "BP601T",
                name: "Advanced Pharmacognosy",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Marine natural products — drugs from marine organisms",
                    "Unit II: Biotransformation of crude drugs; plant cell culture",
                    "Unit III: Novel herbal drug delivery — phytosomes, nanoemulsions",
                    "Unit IV: Pharmacogenomics in personalized herbal medicine",
                    "Unit V: Global herbal medicine regulations — EMA, USFDA, AYUSH guidelines",
                ],
            },
            {
                code: "BP602T",
                name: "Biopharmaceutics and Pharmacokinetics",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Biopharmaceutics — GI absorption factors, BCS classification",
                    "Unit II: Pharmacokinetic models — one and two compartment; non-linear PK",
                    "Unit III: Clearance, Vd, half-life, AUC calculations; multiple dosing equations",
                    "Unit IV: Bioavailability and bioequivalence studies; regulatory guidance",
                    "Unit V: Population PK; TDM; dosage regimen design for special populations",
                ],
            },
            {
                code: "BP603T",
                name: "Intellectual Property Rights",
                credits: 2,
                type: "T",
                units: [
                    "Unit I: Types of IP — patents, trademarks, copyrights, trade secrets",
                    "Unit II: Patent filing in India — PCT, national phase; patentability criteria",
                    "Unit III: Patent analysis tools; freedom-to-operate; pharmaceutical patent strategies",
                    "Unit IV: Technology transfer, licensing agreements, royalties in pharma",
                    "Unit V: Case studies in pharma IP — evergreening, generic drug litigation",
                ],
            },
            {
                code: "BP605T",
                name: "Pharmaceutical Analysis",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: UV-Vis spectrophotometry — Beer-Lambert law, chromophores, assay methods",
                    "Unit II: IR spectroscopy — functional group identification; Raman spectroscopy",
                    "Unit III: NMR spectroscopy — 1H and 13C NMR; interpretation of spectra",
                    "Unit IV: HPLC and GC — principles, types, method development, applications",
                    "Unit V: Mass spectrometry; hyphenated techniques — LC-MS, GC-MS in drug analysis",
                ],
            },
            {
                code: "BP606T",
                name: "Pharmaceutical Jurisprudence",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Drugs & Cosmetics Act 1940 (as amended) — schedules, licensing",
                    "Unit II: Pharmacy Act 1948 — registration, State Pharmacy Councils",
                    "Unit III: NDPS Act 1985 — narcotic drugs, psychotropic substances control",
                    "Unit IV: DPCO — drug price control; Jan Aushadhi; essential medicines list",
                    "Unit V: Medical Devices Rules 2017; Clinical Establishment Act; consumer protection",
                ],
            },
            {
                code: "BP607T-AEC",
                name: "AEC Elective (choose 1 of 6)",
                credits: 1,
                type: "P",
                units: [
                    "AEC1: Green Chemistry — principles, atom economy, solvent selection in pharma",
                    "AEC2: Materiovigilance and Hemovigilance — reporting systems",
                    "AEC3: Scientific Writing — research papers, systematic reviews, grants",
                    "AEC4: Drug Store and Business Management",
                    "AEC5: Career Building in Cultivation of Medicinal Plants",
                    "AEC6: Active Pharmaceutical Ingredients and Excipient Sciences",
                ],
            },
            {
                code: "BP612I",
                name: "Internship II (Mandatory)",
                credits: 4,
                type: "I",
                units: [
                    "Mandatory advanced internship after completing Semester V-VI coursework",
                    "Focus on QA, regulatory affairs, R&D, or clinical pharmacy",
                    "Minimum 120 hours; structured logbook and evaluation",
                    "Industry mentor report; final viva for credit award",
                ],
            },
        ],
    },
    {
        num: 7,
        credits: 26,
        color: "#F97316",
        bg: "#FFF7ED",
        badge: "#FED7AA",
        label: "Pharmacovigilance + Regulatory + Research",
        subjects: [
            {
                code: "BP703T",
                name: "AI in Clinical Applications",
                credits: 2,
                type: "T",
                highlight: true,
                units: [
                    "Unit I: AI-driven clinical decision support systems (CDSS)",
                    "Unit II: EHR analytics — patient data mining, readmission prediction",
                    "Unit III: Medical imaging AI — radiology (CT, MRI), pathology slides analysis",
                    "Unit IV: Predictive analytics for disease progression, ADR risk scoring",
                    "Unit V: Ethics and regulatory aspects of clinical AI; FDA guidance on AI/ML SaMD",
                ],
            },
            {
                code: "BP705T",
                name: "Pharmacovigilance",
                credits: 3,
                type: "T",
                highlight: true,
                units: [
                    "Unit I: Definition, objectives, history; WHO Uppsala Monitoring Centre",
                    "Unit II: ADR classification (WHO, DoTS), causality assessment methods",
                    "Unit III: Signal detection — disproportionality analysis, FAERS, VigiBase",
                    "Unit IV: Risk management plans (RMP), REMS strategies; labeling updates",
                    "Unit V: Indian PvPI program; ICH E2A-E2F guidelines; periodic safety reports (PSUR)",
                ],
            },
            {
                code: "BP707T",
                name: "Regulatory Affairs",
                credits: 2,
                type: "T",
                highlight: true,
                units: [
                    "Unit I: Drug regulatory agencies — CDSCO, USFDA, EMA, TGA, WHO prequalification",
                    "Unit II: NDA/ANDA process — 505(b)(1), 505(b)(2), ANDA filing in USA",
                    "Unit III: CTD format — Module 1-5; eCTD submission requirements",
                    "Unit IV: Clinical trial regulations in India — Schedule Y, CTRI, ethics committee",
                    "Unit V: Good Regulatory Practice (GRP); CDSCO-WHO-THSTI certification overview",
                ],
            },
            {
                code: "BP701T",
                name: "Biostatistics Research Methodology",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Research design — observational (cohort, case-control) vs experimental",
                    "Unit II: Sampling methods, sample size calculation, randomization",
                    "Unit III: Non-parametric tests — Mann-Whitney, Kruskal-Wallis, Wilcoxon",
                    "Unit IV: Clinical research design; ICH GCP E6 guidelines; CRO operations",
                    "Unit V: Scientific writing — IMRAD format, systematic review, meta-analysis",
                ],
            },
            {
                code: "BP702T",
                name: "Cosmetics and Cosmeceuticals",
                credits: 2,
                type: "T",
                units: [
                    "Unit I: Skin biology — layers, skin types, transepidermal water loss",
                    "Unit II: Cosmetic formulations — creams, lotions, serums, shampoos, sunscreens",
                    "Unit III: Active ingredients in cosmeceuticals — retinoids, AHAs, peptides, hyaluronic acid",
                    "Unit IV: Regulatory requirements for cosmetics — Drugs & Cosmetics Act, BIS standards",
                    "Unit V: Safety testing, stability studies and quality control of cosmetic products",
                ],
            },
            {
                code: "BP704T",
                name: "Modern Analytical Techniques",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Thermal analysis — DSC, TGA, DTA applications in polymorphism",
                    "Unit II: X-ray powder diffractometry (XRPD) in pharmaceutical solid-state analysis",
                    "Unit III: Electron microscopy — SEM, TEM for particle characterization",
                    "Unit IV: Capillary electrophoresis; flow injection analysis (FIA)",
                    "Unit V: Hyphenated techniques; analytical method validation as per ICH Q2(R1)",
                ],
            },
            {
                code: "BP706T",
                name: "Pharmacy Practice",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Clinical pharmacy services — medication therapy management, reconciliation",
                    "Unit II: Prescription analysis; medication error prevention strategies",
                    "Unit III: Patient counseling techniques; adherence and compliance strategies",
                    "Unit IV: Hospital pharmacy management — formulary, procurement, distribution",
                    "Unit V: Drug information services — DIC, databases (Micromedex, PubMed, UpToDate)",
                ],
            },
            {
                code: "BP708T-AEC",
                name: "AEC Elective (choose 1 of 6)",
                credits: 1,
                type: "P",
                units: [
                    "AEC1: Current Good Manufacturing Practices (cGMP) — recent updates",
                    "AEC2: Pharmaceutical Automation — Industry 4.0 in pharma manufacturing",
                    "AEC3: Modern Techniques in Cellular Biology",
                    "AEC4: Medical Devices — classification, regulation, MDR 2017",
                    "AEC5: Transformation of Food Waste into Medicinal Products",
                    "AEC6: Biosimilars, Vaccines and Macromolecules",
                ],
            },
            {
                code: "BP710RP",
                name: "Research Project (Major)",
                credits: 6,
                type: "RP",
                units: [
                    "Independent research under faculty guide; topic finalization by Sem 6",
                    "Comprehensive literature review and research proposal",
                    "Data collection, analysis (statistical tools, software)",
                    "Thesis writing as per prescribed format; anti-plagiarism check",
                    "Final presentation and external viva examination",
                ],
            },
        ],
    },
    {
        num: 8,
        credits: 24,
        color: "#BE185D",
        bg: "#FFF1F2",
        badge: "#FECDD3",
        label: "AI Ethics + Clinical + Final Project",
        subjects: [
            {
                code: "BP801T",
                name: "Ethical Considerations and Translational Applications of AI in Pharmacy",
                credits: 2,
                type: "T",
                highlight: true,
                units: [
                    "Unit I: AI ethics — algorithmic bias, fairness, transparency in healthcare AI",
                    "Unit II: Translational AI — bench to bedside; real-world evidence (RWE)",
                    "Unit III: Regulatory frameworks for AI/ML-based medical devices (FDA, EMA guidance)",
                    "Unit IV: AI in pharmacogenomics and precision/personalized medicine",
                    "Unit V: Future of AI in pharmacy education, practice and drug development",
                ],
            },
            {
                code: "BP802T",
                name: "Clinical Pharmacotherapeutics",
                credits: 2,
                type: "T",
                units: [
                    "Unit I: Drug therapy in special populations — pediatrics, geriatrics, pregnancy",
                    "Unit II: Pharmacotherapy of cardiovascular diseases — CHF, ACS, arrhythmias",
                    "Unit III: Pharmacotherapy of endocrine/metabolic disorders — DM, hypothyroidism",
                    "Unit IV: Pharmacotherapy of infectious diseases — sepsis, TB, HIV, fungal",
                    "Unit V: Drug dosing in renal/hepatic impairment; therapeutic monitoring",
                ],
            },
            {
                code: "BP803T",
                name: "Industrial Pharmacy and Facility Design",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Industrial pharmaceutical manufacturing — batch vs continuous",
                    "Unit II: Facility layout and design principles — zones, traffic flow, contamination control",
                    "Unit III: HVAC systems — air handling units, clean room classifications (ISO 5-8)",
                    "Unit IV: Equipment qualification — URS, DQ, IQ, OQ, PQ documentation",
                    "Unit V: Scale-up from lab to pilot to commercial batch — tech transfer challenges",
                ],
            },
            {
                code: "BP804T",
                name: "Pharmaceutical Management",
                credits: 2,
                type: "T",
                units: [
                    "Unit I: Principles of management — POSDCORB functions in pharmaceutical orgs",
                    "Unit II: HR management — recruitment, training, performance appraisal in pharma",
                    "Unit III: Supply chain and inventory management — VED, ABC, JIT analysis",
                    "Unit IV: Pharmaceutical marketing — product positioning, launch strategies",
                    "Unit V: Entrepreneurship — pharma business models, startup valuations, funding",
                ],
            },
            {
                code: "BP805T",
                name: "Sterile Dosage Forms and Novel Drug Delivery System",
                credits: 3,
                type: "T",
                units: [
                    "Unit I: Parenteral products — large/small volume parenterals, packaging, sterilization",
                    "Unit II: Ophthalmic, nasal and pulmonary sterile preparations",
                    "Unit III: Nanoparticulate DDS — polymeric nanoparticles, dendrimers, carbon nanotubes",
                    "Unit IV: Biopolymers in DDS — hydrogels, microspheres, implants",
                    "Unit V: Regulatory requirements for sterile and novel DDS — CTD sections, ICH Q8/Q10",
                ],
            },
            {
                code: "BP806T-AEC",
                name: "AEC Elective (choose 1 of 6)",
                credits: 2,
                type: "P",
                units: [
                    "AEC1: Pharmaceutical Packaging — materials, regulations, sustainability",
                    "AEC2: Supply Chain Management — pharma cold chain, serialization",
                    "AEC3: Industrial Safety and Waste Management — OSHA, EHS in pharma",
                    "AEC4: Traditional Healing Practices of India — Ayurveda, Siddha, Unani overview",
                    "AEC5: Futuristic Pharma through AR/VR — Pharma 4.0 concepts",
                    "AEC6: Herbal Cosmetics for Industry Perspective",
                ],
            },
            {
                code: "BP807P-BP808P",
                name: "Practicals — Marketing Skills + Sterile Dosage Forms",
                credits: 3,
                type: "P",
                units: [
                    "Pharmaceutical Marketing Skills Lab — detailing, presentations, negotiation",
                    "Sterile Dosage Forms Lab — aseptic technique, parenteral preparation, sterility tests",
                    "VAC Elective: Cleaning Validation | Aseptic Handling | Impurity Profiling",
                ],
            },
            {
                code: "BP810RP",
                name: "Research Project (Final Submission)",
                credits: 6,
                type: "RP",
                units: [
                    "Continuation and completion of Semester VII research project",
                    "Final data analysis, statistical validation, discussion and conclusions",
                    "Thesis hard-binding and submission as per university norms",
                    "External examination board viva — research defense",
                    "Publication/conference presentation strongly recommended for distinction",
                ],
            },
        ],
    },
];

export const TYPE_META: Record<string, TypeMeta> = {
    T: { label: "Theory", bg: "#EEF2FF", color: "#3730A3" },
    P: { label: "Practical / Elective", bg: "#F0FDF4", color: "#14532D" },
    I: { label: "Internship", bg: "#FFF7ED", color: "#92400E" },
    RP: { label: "Research Project", bg: "#FAF5FF", color: "#581C87" },
};

/** All semesters with auto-generated SEO-friendly subject slugs. */
export const SEMESTERS: Semester[] = RAW_SEMESTERS.map((sem) => ({
    ...sem,
    subjects: sem.subjects.map((s) => ({
        ...s,
        slug: makeSubjectSlug(s.code, s.name),
    })),
}));

export function getSemester(num: number): Semester | undefined {
    return SEMESTERS.find((s) => s.num === num);
}

export function getSubject(
    semNum: number,
    slug: string,
): { semester: Semester; subject: Subject } | undefined {
    const semester = getSemester(semNum);
    if (!semester) return undefined;
    const subject = semester.subjects.find((s) => s.slug === slug);
    if (!subject) return undefined;
    return { semester, subject };
}

export const TOTAL_CREDITS = SEMESTERS.reduce((acc, s) => acc + s.credits, 0);
export const TOTAL_SUBJECTS = SEMESTERS.reduce(
    (acc, s) => acc + s.subjects.length,
    0,
);
